security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    # --- NOUVEAU BLOC: HIERARCHIE DE RÔLES ---
    role_hierarchy:
        # L'Admin hérite de tout le monde
        ROLE_ADMIN: [ROLE_GESTIONNAIRE] 
        # Le Gestionnaire hérite du Professeur
        ROLE_GESTIONNAIRE: [ROLE_PROF] 
        # Le Professeur pourrait hériter de l'Élève, mais ce n'est généralement pas nécessaire
        ROLE_PROF: [ROLE_ELEVE]
        
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # --- C'EST LA CORRECTION PRINCIPALE ---
        # On dit à Symfony d'utiliser la base de données (Doctrine)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            
            # --- CORRECTION ICI ---
            # On dit au firewall d'utiliser le provider de la base de données
            provider: app_user_provider
            # --- FIN CORRECTION ---

            custom_authenticator: App\Security\LoginFormAuthenticator

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine
                path: /
                # always_remember_me: true # Décommentez si vous ne voulez pas de case à cocher

            # J'ai ajouté la section de déconnexion que vous n'aviez pas
            logout:
                path: app_logout
                target: app_home # Redirige vers la page d'accueil après la déconnexion

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # Protégez le /planning/global via le contrôleur (annotation)
        # Mais ajoutons une ligne pour le niveau Admin, c'est plus sûr
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/professeur/dashboard, roles: ROLE_PROF }
        # - { path: ^/eleve/dashboard, roles: ROLE_ELEVE }
        # - { path: ^/instrument, roles: ROLE_GESTIONNAIRE }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon